# RBAC permissions for the Kyverno background controller
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kyverno-orphaned-service-controller
rules:
# Permission to get/list/update services
- apiGroups: [""]
  resources: ["services"]
  verbs: ["get", "list", "watch", "update", "patch"]
# Permission to get/list endpoints
- apiGroups: [""]
  resources: ["endpoints"]
  verbs: ["get", "list", "watch"]
# Permission to create and manage events - explicitly in all namespaces
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create", "patch", "update", "get", "list", "watch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kyverno-orphaned-service-binding
subjects:
- kind: ServiceAccount
  name: kyverno-background-controller
  namespace: kyverno
- kind: ServiceAccount
  name: kyverno-admission-controller
  namespace: kyverno
roleRef:
  kind: ClusterRole
  name: kyverno-orphaned-service-controller
  apiGroup: rbac.authorization.k8s.io 
---
# RBAC permissions for the Kyverno cleanup controller
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kyverno-cleanup-controller
rules:
# Permission to get/list/delete services
- apiGroups: [""]
  resources: ["services"]
  verbs: ["get", "list", "watch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kyverno-cleanup-binding
subjects:
- kind: ServiceAccount
  name: kyverno-cleanup-controller
  namespace: kyverno
roleRef:
  kind: ClusterRole
  name: kyverno-cleanup-controller
  apiGroup: rbac.authorization.k8s.io
