apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kyverno-cronjob-manager
rules:
  - apiGroups: ["batch"]
    resources: ["cronjobs"]
    verbs: ["create", "update", "delete"]
  - apiGroups: [""]
    resources: ["serviceaccounts"]
    verbs: ["create", "update", "delete"]
  - apiGroups: ["rbac.authorization.k8s.io"]
    resources: ["clusterroles", "clusterrolebindings"]
    verbs: ["create", "update", "delete"]
  - apiGroups: ["apps"]
    resources: ["deployments", "deployments/scale"]
    verbs: ["get", "list", "patch", "update"]
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["create", "delete", "list", "get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kyverno-cronjob-binding
subjects:
  - kind: ServiceAccount
    name: kyverno-background-controller
    namespace: kyverno
roleRef:
  kind: ClusterRole
  name: kyverno-cronjob-manager
  apiGroup: rbac.authorization.k8s.io
