apiVersion: kyverno.io/v2alpha1
kind: ClusterCleanupPolicy
metadata:
  name: cleanup-replicasets
spec:
  match:
    any:
    - resources:
        kinds:
          - ReplicaSet
  exclude:
    any:
    - resources:
        namespaces:
          - kube-system
  conditions:
    all:
    - key: "{{ target.spec.replicas }}"
      operator: Equals
      value: 0
    - key: "{{ time_diff('{{target.metadata.creationTimestamp}}','{{ time_now_utc() }}') }}"
      operator: "GreaterThan"
      value: "720h0m0s"
  schedule: "* * * * *"
