apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  creationTimestamp: null
  name: kyverno-mutate-labels-ns
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kyverno:mutate-labels-ns
subjects:
- kind: ServiceAccount
  name: kyverno-background-controller
  namespace: kyverno
