apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/component: background-controller
    app.kubernetes.io/instance: kyverno-operator
    app.kubernetes.io/part-of: kyverno
  name: kyverno:mutate-labels-ns
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - update
  - get
  - watch
  - list
